[package]
name = "shill_tracker"
version = "0.1.0"
edition = "2021"

[dependencies]
serenity = "0.11"
tokio = { version = "1.20", features = ["rt-multi-thread"] }
tracing = "0.1"
tracing-subscriber = "0.2"